### PR TITLE
Bootstrap doom emacs theme

### PR DESCRIPTION
**Pull request by bersace**
Hi,

I started a Selenized Dark theme for [Doom Emacs](https://github.com/hlissner/doom-emacs). Here is my contribution.

I didn't submit this theme to hlissner/emacs-doom-themes to share design and iterate with selenized community.

Screenshot attached to PR.

What do you think of this ?

screenshot

### CODE REVIEW

**Comment by jan-warchol** [comment]
Nice! Thanks for providing the screenshot, it is helpful. Generally looks sensible.

1. Can you make comments italic?
2. There's [a discussion](https://github.com/jan-warchol/selenized/issues/74) whether keywords should be green or yellow. Could you please make them yellow, and use green for the things that are yellow now?
3. Could you make a screenshot using code samples from [this repo](https://github.com/jan-warchol/highlighting-code-samples)? I'm very familar with them and it'll help me in making a detailed review. Python, ruby, javascript and bash (from root dir) will be fine, no need for more.

**Comment by bersace** [comment]
@jan-warchol thanks for the review. I applied your suggestions and fixed magenta color. Screenshot is updated and added to PR description.

**Comment by simendsjo** [comment]
I tried this theme now, and notice some colors have a bad contrast.

Selenized: 
image

Solarized: 
image

**Comment by simendsjo** [comment]
Looks like the same gray is used other places, like in the magit header:
image
PS: Only using git as a backup here -- I use commit messages in production :)

**Comment by bersace** [comment]
Hi @simendsjo thanks for the feedback. This theme is just a starting point. Contribution welcome :-)

**Pull request closed without merging**
